### ISSUE TITLE
kvm 설치하는중 에러가 발생했습니다

### ISSUE THREAD

**Issue by ksm9413** [developer-onizuka/gpudirect_storage_1.0_VirtualMachine#2]
root@syseng-desktop:/# virt-manager
root@syseng-desktop:/# No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(virt-manager:80191): Gtk-WARNING **: 15:16:03.119: cannot open display: :11.0

============================================

As shown in the guide, I installed what I needed and ran the virt-manager command, and the above message was displayed.
How can I fix that error?

**Comment by developer-onizuka** [comment]
I believe it came from environment settings.
You might start virt-manager after "export DISPLAY=:0.0". Your error is not GDS problem.

**Comment by ksm9413** [comment]
Still getting the same error


root@syseng-desktop:/# export DISPLAY=:0.0
root@syseng-desktop:/# virt-manager
root@syseng-desktop:/# No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(virt-manager:198502): Gtk-WARNING **: 16:26:51.189: cannot open display: :0.0

**Comment by developer-onizuka** [comment]
I'm not sure about your machine, but if you connect remotely you might try on the desktop machine directly. 
Sorry for no good solution for you.
